# Generated by Django 6.1 on 2026-08-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trailer_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
